"""add transactions table

Revision ID: c94a1bb14bb7
Revises: 9a3f39b4a274
Create Date: 2026-07-04 18:24:03.490817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c94a1bb14bb7'
down_revision: Union[str, Sequence[str], None] = '9a3f39b4a274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('institution_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transaction_categories',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('sub_accounts',
    sa.Column('sub_account_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('sub_account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sa.Enum('idr', 'usd', 'sgd', name='currency'), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('sub_account_id'),
    sa.UniqueConstraint('sub_account_name')
    )
    op.create_table('cards',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('sub_account_id', sa.Integer(), nullable=False),
    sa.Column('card_number_masked', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sub_account_id'], ['sub_accounts.sub_account_id'], ),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('card_number_masked')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('sub_account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('trx_date', sa.Date(), nullable=False),
    sa.Column('trx_time', sa.Time(timezone=True), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sa.Enum('idr', 'usd', 'sgd', name='currency'), nullable=False),
    sa.Column('counterparty_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('counterparty_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trx_reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('running_balance', sa.Float(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('settlement_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['transaction_categories.category_id'], ),
    sa.ForeignKeyConstraint(['sub_account_id'], ['sub_accounts.sub_account_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('trx_reference_id')
    )
    op.create_index('ix_trx_category', 'transactions', ['category_id'], unique=False)
    op.create_index('ix_trx_subaccount_date', 'transactions', ['sub_account_id', 'trx_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trx_subaccount_date', table_name='transactions')
    op.drop_index('ix_trx_category', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('cards')
    op.drop_table('sub_accounts')
    op.drop_table('accounts')
    op.drop_table('transaction_categories')
    op.drop_table('institutions')
    # ### end Alembic commands ###
